[workspace]
resolver = "2"
members = [
    "tosho",
    "tosho_musq",
    "tosho_kmkc",
    "tosho_amap",
    "tosho_macros"
]

[workspace.package]
version = "0.2.1"
edition = "2021"
authors = ["noaione <noaione@n4o.xyz>"]
license = "MIT"

[workspace.dependencies]
tokio = { version = "1.35.1", features = ["full"] }
reqwest = "0.11.23"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
prost = "0.12"
prost-types = "0.12"
lazy_static = "1"
anyhow = "1"
base64 = "0.21.5"
chrono = "0.4"
futures-util = "0.3"
cookie_store = "0.20.0"
reqwest_cookie_store = "0.6.0"
sha2 = "0.10.8"
time = "0.3.31"

# CI-PROFILE-MARK
