[workspace]
resolver = "2"
members = [
    "tosho",
    "tosho_musq",
    "tosho_kmkc",
    "tosho_amap",
    "tosho_macros"
]

[workspace.package]
version = "0.2.4-dev"
edition = "2021"
authors = ["noaione <noaione@n4o.xyz>"]
license = "MIT"

[workspace.dependencies]
tokio = { version = "1.35.1", features = ["full"] }
reqwest = { version = "0.11.24", features = ["socks"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
prost = "0.12.3"
prost-types = "0.12.3"
lazy_static = "1"
anyhow = "1"
base64 = "0.21.7"
chrono = "0.4"
futures-util = "0.3"
cookie_store = "0.20.0"
reqwest_cookie_store = "0.6.0"
sha2 = "0.10.8"
time = "0.3.34"

# CI-PROFILE-MARK
