name: 🐞 Issue report
description: Report an issue with tosho.
labels: [x-triage]

body:
  - type: dropdown
    id: source-problems
    attributes:
      label: Problems with
      description: |
        The source you are having problems with.
      multiple: true
      options:
        - Core (CLI related)
        - 'Source: AMAP (am)'
        - 'Source: KMKC (km)'
        - 'Source: MUSQ (mu)'
        - Other (provide at the end)
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: tosho-version
    attributes:
      label: tosho version
      description: |
        You can find your `tosho` version with `tosho -V` in a terminal.
      placeholder: |
        Example: "0.4.2"
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: |
        The operating system you are using.
      placeholder: |
        Example: "Windows 11"
    validations:
      required: true

  - type: dropdown
    id: downloaded-from
    attributes:
      label: Obtained from
      description: |
        Where did you obtain/download tosho from?
      multiple: false
      options:
        - GitHub Releases ("Stable")
        - GitHub Actions ("Nightly")
        - Build from source
        - other (provide below)
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to version **[0.4.2](https://github.com/noaione/tosho-mango/releases)**.
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true
