name: CI
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_SYSROOT_DIR: /
permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    # do not run if commit starts with docs:
    if: ${{ !startsWith(github.event.head_commit.message, 'docs:') }}
    steps:
      - name: Cancel tasks
        uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml

  tests:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup rust cache
        uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8
        with:
          prefix-key: "${{ runner.os }}-tosho-rust"

      - name: Build
        run: cargo build --verbose --all

      - name: Lint
        run: cargo clippy --verbose --all -- -D warnings

      - name: Test
        run: cargo test --verbose --all

  build:
    needs: [prepare, tests]
    strategy:
      matrix:
        os:
          # GNU Linux (x64)
          - [ubuntu-latest, x86_64-unknown-linux-gnu]
          # macOS Intel (x64)
          - [macos-latest, x86_64-apple-darwin]
          # macOS Apple Silicon (ARM64)
          - [macos-latest, aarch64-apple-darwin]
          # Windows 10 (x64)
          - [windows-latest, x86_64-pc-windows-msvc]
      fail-fast: false
    
    runs-on: ${{ matrix.os[0] }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Rust Target
        run: |
          rustup target add ${{ matrix.os[1] }}

      - name: Setup rust cache
        uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8
        with:
          prefix-key: "${{ runner.os }}-${{ matrix.os[1] }}-tosho-build-rust"

      - name: Build (Nightly)
        run: |
          sed -i'' -e 's/# CI-PROFILE-MARK/[profile.release]\nopt-level = "z"\nlto = true\ncodegen-units = 1\npanic = "abort"/g' Cargo.toml
          cargo build --release --verbose --all --target ${{ matrix.os[1] }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tosho-${{ matrix.os[1] }}
          path: |
            target/${{ matrix.os[1] }}/release/tosho.exe
            target/${{ matrix.os[1] }}/release/tosho

      - name: Build (Release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cargo build --release --verbose --all --target ${{ matrix.os[1] }}
        shell: bash
        env:
          RELEASE: true

      - name: Prepare release
        if: matrix.os[0] != 'windows-latest'
        shell: bash
        run: |
          cd target/${{ matrix.os[1] }}/release
          tar -czvf tosho-${{ matrix.os[1] }}.tar.gz tosho
          cd ../../..

      - name: Prepare release (Win32)
        if: matrix.os[0] == 'windows-latest'
        run: |
          cd target/${{ matrix.os[1] }}/release
          Compress-Archive -Path tosho.exe -DestinationPath tosho-${{ matrix.os[1] }}.zip
          cd ../../..

      - name: Create changelog
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          python3 scripts/create_changelog.py
        env:
          VERSION: ${{ github.ref }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            target/${{ matrix.os[1] }}/release/tosho-${{ matrix.os[1] }}.zip
            target/${{ matrix.os[1] }}/release/tosho-${{ matrix.os[1] }}.tar.gz
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: CHANGELOG-GENERATED.md
