name: CI
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
  merge_group:

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_SYSROOT_DIR: /
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'docs:') }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90
        with:
          submodules: 'true'

      - name: Rustup stable
        run: |
          rustup update stable

      - name: Setup rust cache
        uses: Swatinem/rust-cache@640a22190e7a783d4c409684cea558f081f92012
        with:
          prefix-key: "${{ runner.os }}-airpope-rust"

      - name: Build
        run: cargo build --verbose --all

      - name: Test
        run: cargo test --verbose --all

  build:
    needs: tests
    strategy:
      matrix:
        os:
          # GNU Linux (x64)
          - [ubuntu-latest, x86_64-unknown-linux-gnu]
          # macOS Intel (x64)
          - [macos-12, x86_64-apple-darwin]
          # macOS Apple Silicon (ARM64)
          - [macos-14, aarch64-apple-darwin]
          # Windows 10 (x64)
          - [windows-latest, x86_64-pc-windows-msvc]
      fail-fast: false
    
    runs-on: ${{ matrix.os[0] }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90

      - name: Rust Target
        run: |
          rustup update stable
          rustup target add ${{ matrix.os[1] }}

      - name: Setup rust cache
        uses: Swatinem/rust-cache@640a22190e7a783d4c409684cea558f081f92012
        with:
          prefix-key: "${{ runner.os }}-${{ matrix.os[1] }}-airpope-build-rust"

      - name: Prepare build
        if: matrix.os[0] != 'windows-latest'
        run: |
          sed -i'' -e 's/# CI-PROFILE-MARK/[profile.release]\nopt-level = "z"\nlto = true\ncodegen-units = 1\npanic = "abort"\nstrip = "debuginfo"/g' Cargo.toml
        shell: bash

      - name: Prepare build (Win32)
        if: matrix.os[0] == 'windows-latest'
        run: |
          sed -i'' -e 's/# CI-PROFILE-MARK/[profile.release]\nopt-level = "z"\nlto = true\ncodegen-units = 1\npanic = "abort"/g' Cargo.toml

      - name: Build (Nightly)
        if: startsWith(github.ref, 'refs/tags/v') != true
        run: |
          cargo build --release --verbose --all --target ${{ matrix.os[1] }}
        shell: bash

      - name: Permissions (Nightly)
        if: startsWith(github.ref, 'refs/tags/v') != true && matrix.os[0] != 'windows-latest'
        run: |
          chmod +x target/${{ matrix.os[1] }}/release/airpope
        shell: bash

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: actions/upload-artifact@ef09cdac3e2d3e60d8ccadda691f4f1cec5035cb
        with:
          name: airpope-${{ matrix.os[1] }}
          path: |
            target/${{ matrix.os[1] }}/release/airpope.exe
            target/${{ matrix.os[1] }}/release/airpope

      - name: Build (Release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cargo build --release --verbose --all --target ${{ matrix.os[1] }}
        shell: bash
        env:
          RELEASE: true

      - name: Prepare release
        if: matrix.os[0] != 'windows-latest' && startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          cd target/${{ matrix.os[1] }}/release
          chmod +x airpope
          tar -czvf airpope-${{ matrix.os[1] }}.tar.gz airpope
          mv airpope-${{ matrix.os[1] }}.tar.gz ../../..
          cd ../../..

      - name: Prepare release (Win32)
        if: matrix.os[0] == 'windows-latest' && startsWith(github.ref, 'refs/tags/v')
        run: |
          cd target/${{ matrix.os[1] }}/release
          Compress-Archive -Path airpope.exe -DestinationPath airpope-${{ matrix.os[1] }}.zip
          mv airpope-${{ matrix.os[1] }}.zip ../../..
          cd ../../..

      - name: Upload artifact
        uses: actions/upload-artifact@ef09cdac3e2d3e60d8ccadda691f4f1cec5035cb
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: airpope-packages-${{ matrix.os[1] }}
          path: |
            airpope-${{ matrix.os[1] }}.zip
            airpope-${{ matrix.os[1] }}.tar.gz

  releases:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') && github.repository_owner == 'noaione'
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90

      - name: Download artifacts
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427
        with:
          path: airpope-packages
          pattern: airpope-packages-*
          merge-multiple: true

      - name: Create changelog
        id: prepare-change
        run: |
          python3 scripts/create_changelog.py
          # Fetch git tag contents subject
          VERSION_SUBJ=$(git tag -l --format='%(contents:subject)' ${{ github.ref }})
          echo "version_subject=$VERSION_SUBJ" >> "$GITHUB_OUTPUT"
        env:
          VERSION: ${{ github.ref }}

      - name: Release
        uses: softprops/action-gh-release@975c1b265e11dd76618af1c374e7981f9a6ff44a
        with:
          files: |
            airpope-packages/*
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: CHANGELOG-GENERATED.md
          name: ${{ steps.prepare-change.outputs.version_subject }}

      - name: Create discussions
        uses: nvdaes/build-discussion@016eda27862486e315a0b110b72add08bd11a916
        with:
          title: Release ${{ github.ref_name }}
          body: |
            Release **${{ github.ref_name }}** is now available for **[download](https://github.com/noaione/airpope-mango/releases/tag/${{ github.ref_name }})**.

            Please see the [changelog](https://github.com/noaione/airpope-mango/blob/master/CHANGELOG.md) for more information.

            Report any issues you found in the [issue tracker](https://github.com/noaione/airpope-mango/issues/new/choose)
          category-position: 1  # Announcements
