name: Publish to crates.io
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true
        default: 'latest'

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_SYSROOT_DIR: /
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Publish to crates.io
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        if: inputs.tag == 'latest'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Checkout repo (tag)
        if: inputs.tag != 'latest'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ inputs.tag }}

      - name: Prepare Python
        run: |
          pip3 install requests toml

      - name: Publish
        run: |
          python3 -u scripts/crates_publish.py
        env:
          RELEASE: true
          CARGO_REGISTRY_TOKEN: ${{ secrets.RUST_CARGO_REGISTRY }}
